#ifndef _MIRROS_H
#define _MIRROS_H

#include <config/config.h>

#define PROCESS_USER_BASE		(0X00000000)
#define PROCESS_USER_ELF_SIZE		(512 * 1024 *1024)

#define PROCESS_USER_SO_BASE		(PROCESS_USER_BASE + PROCESS_USER_ELF_SIZE)
#define PROCESS_USER_SO_SIZE		(768 * 1024 * 1024)

#define PROCESS_USER_MMAP_BASE		(PROCESS_USER_SO_BASE + PROCESS_USER_SO_SIZE)
#define PROCESS_USER_MMAP_SIZE		(512 * 1024 * 1024)
#define PROCESS_USER_MMAP_END		(PROCESS_USER_MMAP_BASE + PROCESS_USER_MMAP_SIZE)

#define PROCESS_USER_STACK_BASE		(0x80000000)
#define PROCESS_STACK_SIZE		(128 * 1024 * 1024)

/*
 * define the struct of elf zone
 */
#define PROCESS_USER_ELF_UNUSED_SIZE	(4 * 1024 * 1024)
#define PROCESS_USER_META_BASE		(PROCESS_USER_BASE + PROCESS_USER_ELF_UNUSED_SIZE)
#define PROCESS_USER_META_SIZE		(16 * 1024)
#define PROCESS_SIGRETURN_OFFSET	(3000)
#define PROCESS_USER_EXEC_BASE		(0x00404000)

#endif
